image: reg.handtruth.com/ktlo/mcshub/build-tools:gcc-8

stages:
  - build
  - test
  - package
  - docker
  - deploy

BuildX86_64:
  stage: build
  script:
    - sed -i '1s/^/prefix=x86_64-linux-gnu- /' config
    - make
  tags: ["default"]
  artifacts:
    paths:
      - out/mcshub
    expire_in: 1 week

BuildArmhf:
  stage: build
  script:
    - sed -i '1s/^/prefix=arm-linux-gnueabihf- /' config
    - make
  tags: ["default"]
  artifacts:
    paths:
      - out/mcshub
    expire_in: 1 week

TestX86_64:
  stage: test
  script:
    - sed -i '1s/^/prefix=x86_64-linux-gnu- /' config
    - make tests
  tags: ["default"]

cache:
  paths:
    - dep
