FROM alpine:latest
ADD out/mcshub /usr/local/bin/mcshub
RUN mkdir /mcshub && apk --no-cache --no-progress add libstdc++
WORKDIR /mcshub
VOLUME /mcshub
EXPOSE 25565/tcp
LABEL maintainer="ktlo@handtruth.com"
ENTRYPOINT [ "mcshub" ]
