#!/bin/bash

context="$1"

if [ $# -ne 1 ]; then
	>&2 echo "one arguments expected"
	exit 1
fi
if [ ! -e "$context" ]; then
	>&2 echo "no such file or directory"
	exit 1
fi

strindex() {
	x="${1%%$2*}"
	[[ "$x" = "$1" ]] && echo -1 || echo "${#x}"
}

insert_file() {
	echo '"'
	while IFS= read line; do
		echo "R\"###($line)###\"" "\"\n\""
	done
	echo -n '"'
}

while IFS= read line; do
	i=`strindex "$line" '${'`
	if [ $i = -1 ]; then
		echo "$line"
	else
		echo -n "${line:0:$i}"
		j=`strindex "$line" '}'`
		path=`realpath "$context/${line:$i + 2:$j - $i - 2}"`
		if [ -f "$path" ]; then
			>&2 echo "include content of: $path"
			cat "$path" | insert_file
			echo "${line:$j + 1}"
		else
			>&2 echo "file don't exists: $path"
			echo "${line:$i}"
		fi
	fi
done
