#!/bin/bash

. config

if [ -f "config.local" ]; then
	. config.local
fi

mkdir dep
cd dep
if [ ! -z "$compiler_version" ]; then
	compiler_version="-$compiler_version"
fi
yaml_cpp=${prefix}yaml-cpp
if [ -f "$yaml_cpp.dep" ]; then
	echo "Yaml-cpp is installed, ommiting..."
else
	echo "Downloading yaml-cpp dependency..."
	wget -q https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-$yaml_cpp_version.tar.gz
	tar -zxf yaml-cpp-$yaml_cpp_version.tar.gz
	mv yaml-cpp-yaml-cpp-$yaml_cpp_version $yaml_cpp
	echo "Building yaml-cpp..."
	mkdir $yaml_cpp/lib
	cd $yaml_cpp/lib
	CC="${prefix}gcc${compiler_version}" CXX="${prefix}g++${compiler_version}" cmake ..
	make
	cd ../..
	touch "$yaml_cpp.dep"
fi
echo "All the dependencies has been installed"
