#!/bin/bash

if [ $# -lt 1 ]; then
	>&2 echo "at least 1 argument required"
	exit -1
fi

name="$1"
file="`pwd`/$name"

shift
cd ../res

cat > "$file" << EOF
#ifndef _RESOURCES_FILE
#define _RESOURCES_FILE

EOF

echo "#include \"$name\""
echo

cat << EOF | tee -a "$file"
namespace mcshub {
	namespace res {

EOF

for filename in `find -type f`; do
	>&2 echo Add resource file: "$filename"
	resource=`realpath --relative-to=. "$filename"`
	var=`tr "/ ." _ <<< "$resource"`
	cat >> "$file" << EOF
		extern const unsigned char $var[];
		extern const unsigned int ${var}_len;

EOF
	xxd -i "$resource" | while IFS= read line; do
		if [[ $line == unsigned* ]]; then
			echo -e "\t\tconst $line"
		else
			echo -e "\t\t$line"
		fi
	done
	echo
done

cat << EOF | tee -a "$file"
	}
}
EOF

echo "#endif // _RESOURCES_FILE" >> "$file"
