#!/bin/bash

mkdir -p dep
cd dep

yaml_cpp=${TARGET}-yaml_cpp

if [ -f "$yaml_cpp.dep" ]; then
	echo "Yaml-cpp is installed, ommiting..."
else
	echo "Building yaml-cpp..."
	mkdir -p lib/$TARGET
	cd lib/$TARGET
	cmake -DYAML_CPP_BUILD_TESTS=OFF ../../yaml_cpp
	make
	cd -
	touch "$yaml_cpp.dep"
fi
echo "All the dependencies has been installed"
